// Updates the progress block at the top of docs/PLAN.md from its checkboxes.
// Run with: npm run progress   (or: node scripts/progress.mjs)
import { readFileSync, writeFileSync } from 'node:fs';

const FILE = new URL('../docs/PLAN.md', import.meta.url);
const START = '<!-- progress:start -->';
const END = '<!-- progress:end -->';

const text = readFileSync(FILE, 'utf8');
const steps = [];
let cur = null;

for (const line of text.split('\n')) {
  const h = line.match(/^### Step (\d+): (.+)$/);
  if (h) {
    cur = { n: Number(h[1]), title: h[2].trim(), build: [], hasReview: false, reviewDone: false };
    steps.push(cur);
    continue;
  }
  if (/^#{1,3} /.test(line)) { cur = null; continue; }
  if (!cur) continue;
  const c = line.match(/^- \[([ xX])\] (.+)$/);
  if (!c) continue;
  const done = c[1].toLowerCase() === 'x';
  if (/owner review/i.test(c[2])) { cur.hasReview = true; cur.reviewDone = done; }
  else cur.build.push(done);
}

const bar = (pct, width) => {
  const filled = Math.round((pct / 100) * width);
  return '█'.repeat(filled) + '░'.repeat(width - filled);
};

let totalAll = 0, doneAll = 0, approved = 0;
const rows = steps.map((s) => {
  const buildDone = s.build.filter(Boolean).length;
  const total = s.build.length + (s.hasReview ? 1 : 0);
  const done = buildDone + (s.reviewDone ? 1 : 0);
  const pct = total ? Math.round((done / total) * 100) : 0;
  totalAll += total; doneAll += done;
  let status = 'Not started';
  if (s.reviewDone) { status = 'Approved'; approved += 1; }
  else if (buildDone === s.build.length && s.build.length > 0) status = 'Ready for your review';
  else if (buildDone > 0) status = 'In progress';
  s.status = status;
  return `| ${s.n} | ${s.title} | ${bar(pct, 10)} ${String(pct).padStart(3)}% | ${status} |`;
});

const overall = totalAll ? Math.round((doneAll / totalAll) * 100) : 0;
const next = steps.find((s) => s.status !== 'Approved');
const today = new Date().toISOString().slice(0, 10);

const block = [
  START,
  `**Overall progress: ${bar(overall, 20)} ${overall}%**  (${doneAll} of ${totalAll} tasks, ${approved} of ${steps.length} steps approved)`,
  '',
  next ? `**Next up:** Step ${next.n}, ${next.title} (${next.status.toLowerCase()})` : '**All steps approved.**',
  '',
  '| Step | What | Progress | Status |',
  '|---|---|---|---|',
  ...rows,
  '',
  `_Last updated ${today}. Generated by scripts/progress.mjs; do not edit this block by hand._`,
  END,
].join('\n');

const a = text.indexOf(START);
const b = text.indexOf(END);
if (a === -1 || b === -1) { console.error('Progress markers not found in docs/PLAN.md'); process.exit(1); }
writeFileSync(FILE, text.slice(0, a) + block + text.slice(b + END.length));
console.log(`Progress: ${overall}% (${doneAll}/${totalAll} tasks, ${approved}/${steps.length} steps approved)`);
